version: '3.8'

networks:
  default:
    driver: bridge

volumes:
  db-volume:

services:
  http:
    build:
      context: .
      dockerfile: docker-compose/nginx/Dockerfile
    container_name: ld-nginx
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ./source:/var/www/html:delegated
    depends_on:
      - app
      - db
      - redis

  db:
    image: "postgres:13.1-alpine"
    container_name: ld-db
    restart: unless-stopped
    tty: true
    ports:
      - "${DB_PORT}:5432"
    environment:
      TZ: "Asia/Vladivostok"
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: "/var/lib/postgresql/data"
    volumes:
      - db-volume:/var/lib/postgresql/data

  redis:
    image: "redis:6.2.0-alpine"
    container_name: ld-redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT}:6379"

  app: &app
    build:
      context: .
      dockerfile: docker-compose/php/Dockerfile
    container_name: ld-app
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - ./source:/var/www/html:delegated
    #ports:
    #  - "9000:9000"
